version: 4
mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://mqtt
serial:
    # Go to the /dev directory and find ttyUSBX
    port: /dev/ttyUSB0
    adapter: ezsp
advanced:
    channel: 11
    network_key: GENERATE
    pan_id: GENERATE
    ext_pan_id: GENERATE
    log_level: info
frontend:
    enabled: true
homeassistant:
    enabled: false