version: '3.8'
services:
    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        logging:
            options:
                max-size: "1m"
        volumes:
            - '/var/docker-volume/home-automation-transmitter/mosquitto:/mosquitto'
        ports:
            - '1883:1883'
            - '9001:9001'
        command: 'mosquitto -c /mosquitto-no-auth.conf'

    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt:2.1.1
        logging:
            options:
                max-size: "1m"
        volumes:
            - /var/docker-volume/home-automation-transmitter/zigbee2mqtt:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0